image: docker:20.10.16
variables:
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:20.10.16-dind
before_script:
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
build:
  stage: build
  script:
    - docker run -t -v $(pwd)/pkguser:/home/pkguser thalhalla/archbuilder bash ./build.sh
    - docker run -t -v $(pwd)/pkguser:/home/pkguser thalhalla/archbuilder bash -c "ls -alh"
    - ls -alh pkguser
